# Generated by Django 3.2.12 on 2022-07-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esposo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_de_nacimiento', models.CharField(max_length=50)),
                ('residencia', models.CharField(max_length=20)),
                ('profesion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_de_nacimiento', models.CharField(max_length=50)),
                ('residencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hermano_mayor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_de_nacimiento', models.CharField(max_length=50)),
                ('residencia', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('estudio', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_de_nacimiento', models.CharField(max_length=10)),
                ('residencia', models.CharField(max_length=50)),
                ('hijos', models.IntegerField()),
            ],
        ),
    ]
